/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entite.User;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URL;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import javax.mail.MessagingException;
import Service.UserDAO;
import GUI.EspaceSanteBienEtre;
import static GUI.EspaceSanteBienEtre.loginScene;
import static GUI.EspaceSanteBienEtre.loginWindow;
import static GUI.EspaceSanteBienEtre.stage;
import tray.notification.NotificationType;
import tray.notification.TrayNotification;
import Utils.AnimationGenerator;
import Utils.Mail;



public class ForgetPasswordController implements Initializable {

    @FXML
    private Button buttonError;
    @FXML
    private TextField email;
    @FXML
    private Button buttonMail;
    @FXML
    private Button buttonAnnuler;
    AnimationGenerator animationGenerator= new AnimationGenerator();
    /**
     * Initializes the controller class.
     */
   

    @FXML
    private void disableAlert(MouseEvent event) {
                buttonError.setVisible(false);

    }

    @FXML
    private void SendMail(ActionEvent event)throws UnsupportedEncodingException, MessagingException {
         Mail m = new Mail();
        UserDAO userDAO = new UserDAO();
        User user = new User();
        String s ="";
      
        user = userDAO.findByEmail(email.getText());
       
      
        
        
         System.out.println(user.getId());
        if( !user.equals(null)  ) {
           
            buttonError.setText("Veuillez verifier votre boite mail");
        buttonError.setVisible(true);
        
        m.Send(user.getEmail(), "								                  		<a target='_blank' href=\""
                    + "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n"
                + "\n"
                + "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                + "<head>\n"
                + "	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n"
                + "	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n"
                + "	<title>[SUBJECT]</title>\n"
                + "	<style type=\"text/css\">\n"
                + "\n"
                + "@media screen and (max-width: 600px) {\n"
                + "    table[class=\"container\"] {\n"
                + "        width: 95% !important;\n"
                + "    }\n"
                + "}\n"
                + "\n"
                + "	#outlook a {padding:0;}\n"
                + "		body{width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0;}\n"
                + "		.ExternalClass {width:100%;}\n"
                + "		.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;}\n"
                + "		#backgroundTable {margin:0; padding:0; width:100% !important; line-height: 100% !important;}\n"
                + "		img {outline:none; text-decoration:none; -ms-interpolation-mode: bicubic;}\n"
                + "		a img {border:none;}\n"
                + "		.image_fix {display:block;}\n"
                + "		p {margin: 1em 0;}\n"
                + "		h1, h2, h3, h4, h5, h6 {color: black !important;}\n"
                + "\n"
                + "		h1 a, h2 a, h3 a, h4 a, h5 a, h6 a {color: blue !important;}\n"
                + "\n"
                + "		h1 a:active, h2 a:active,  h3 a:active, h4 a:active, h5 a:active, h6 a:active {\n"
                + "			color: red !important; \n"
                + "		 }\n"
                + "\n"
                + "		h1 a:visited, h2 a:visited,  h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited {\n"
                + "			color: purple !important; \n"
                + "		}\n"
                + "\n"
                + "		table td {border-collapse: collapse;}\n"
                + "\n"
                + "		table { border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; }\n"
                + "\n"
                + "		a {color: #000;}\n"
                + "\n"
                + "		@media only screen and (max-device-width: 480px) {\n"
                + "\n"
                + "			a[href^=\"tel\"], a[href^=\"sms\"] {\n"
                + "						text-decoration: none;\n"
                + "						color: black; /* or whatever your want */\n"
                + "						pointer-events: none;\n"
                + "						cursor: default;\n"
                + "					}\n"
                + "\n"
                + "			.mobile_link a[href^=\"tel\"], .mobile_link a[href^=\"sms\"] {\n"
                + "						text-decoration: default;\n"
                + "						color: orange !important; /* or whatever your want */\n"
                + "						pointer-events: auto;\n"
                + "						cursor: default;\n"
                + "					}\n"
                + "		}\n"
                + "\n"
                + "\n"
                + "		@media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {\n"
                + "			a[href^=\"tel\"], a[href^=\"sms\"] {\n"
                + "						text-decoration: none;\n"
                + "						color: blue; /* or whatever your want */\n"
                + "						pointer-events: none;\n"
                + "						cursor: default;\n"
                + "					}\n"
                + "\n"
                + "			.mobile_link a[href^=\"tel\"], .mobile_link a[href^=\"sms\"] {\n"
                + "						text-decoration: default;\n"
                + "						color: orange !important;\n"
                + "						pointer-events: auto;\n"
                + "						cursor: default;\n"
                + "					}\n"
                + "		}\n"
                + "\n"
                + "		@media only screen and (-webkit-min-device-pixel-ratio: 2) {\n"
                + "			/* Put your iPhone 4g styles in here */\n"
                + "		}\n"
                + "\n"
                + "		@media only screen and (-webkit-device-pixel-ratio:.75){\n"
                + "			/* Put CSS for low density (ldpi) Android layouts in here */\n"
                + "		}\n"
                + "		@media only screen and (-webkit-device-pixel-ratio:1){\n"
                + "			/* Put CSS for medium density (mdpi) Android layouts in here */\n"
                + "		}\n"
                + "		@media only screen and (-webkit-device-pixel-ratio:1.5){\n"
                + "			/* Put CSS for high density (hdpi) Android layouts in here */\n"
                + "		}\n"
                + "		/* end Android targeting */\n"
                + "		h2{\n"
                + "			color:#181818;\n"
                + "			font-family:Helvetica, Arial, sans-serif;\n"
                + "			font-size:22px;\n"
                + "			line-height: 22px;\n"
                + "			font-weight: normal;\n"
                + "		}\n"
                + "		a.link1{\n"
                + "\n"
                + "		}\n"
                + "		a.link2{\n"
                + "			color:#fff;\n"
                + "			text-decoration:none;\n"
                + "			font-family:Helvetica, Arial, sans-serif;\n"
                + "			font-size:16px;\n"
                + "			color:#fff;border-radius:4px;\n"
                + "		}\n"
                + "		p{\n"
                + "			color:#555;\n"
                + "			font-family:Helvetica, Arial, sans-serif;\n"
                + "			font-size:16px;\n"
                + "			line-height:160%;\n"
                + "		}\n"
                + "	</style>\n"
                + "\n"
                + "<script type=\"colorScheme\" class=\"swatch active\">\n"
                + "  {\n"
                + "    \"name\":\"Default\",\n"
                + "    \"bgBody\":\"ffffff\",\n"
                + "    \"link\":\"fff\",\n"
                + "    \"color\":\"555555\",\n"
                + "    \"bgItem\":\"ffffff\",\n"
                + "    \"title\":\"181818\"\n"
                + "  }\n"
                + "</script>\n"
                + "\n"
                + "</head>\n"
                + "<body>\n"
                + "	<!-- Wrapper/Container Table: Use a wrapper table to control the width and the background color consistently of your email. Use this approach instead of setting attributes on the body tag. -->\n"
                + "	<table cellpadding=\"0\" width=\"100%\" cellspacing=\"0\" border=\"0\" id=\"backgroundTable\" class='bgBody'>\n"
                + "	<tr>\n"
                + "		<td>\n"
                + "	<table cellpadding=\"0\" width=\"620\" class=\"container\" align=\"center\" cellspacing=\"0\" border=\"0\">\n"
                + "	<tr>\n"
                + "		<td>\n"
                + "		<!-- Tables are the most common way to format your email consistently. Set your table widths inside cells and in most cases reset cellpadding, cellspacing, and border to zero. Use nested tables as a way to space effectively in your message. -->\n"
                + "		\n"
                + "\n"
                + "		<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" width=\"600\" class=\"container\">\n"
                + "			<tr>\n"
                + "				<td class='movableContentContainer bgItem'>\n"
                + "\n"
                + "					<div class='movableContent'>\n"
                + "						<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" width=\"600\" class=\"container\">\n"
                + "							<tr height=\"40\">\n"
                + "								<td width=\"200\">&nbsp;</td>\n"
                + "								<td width=\"200\">&nbsp;</td>\n"
                + "								<td width=\"200\">&nbsp;</td>\n"
                + "							</tr>\n"
                + "							<tr>\n"
                + "								<td width=\"200\" valign=\"top\">&nbsp;</td>\n"
                + "								<td width=\"200\" valign=\"top\" align=\"center\">\n"
                + "									<div class=\"contentEditableContainer contentImageEditable\">\n"
                + "					                	<div class=\"contentEditable\" align='center' >\n"
                + "					                  		<img src=\"https://cmkt-image-prd.global.ssl.fastly.net/0.1.0/ps/2900726/300/200/m1/fpnw/wm0/preview1-.png?1498590526&s=fb7cef55a0778485d851ff457ada871e\" width=\"200\" height=\"155\"  alt='Logo'  data-default=\"placeholder\" />\n"
                + "					                	</div>\n"
                + "					              	</div>\n"
                + "								</td>\n"
                + "								<td width=\"200\" valign=\"top\">&nbsp;</td>\n"
                + "							</tr>\n"
                + "							<tr height=\"25\">\n"
                + "								<td width=\"200\">&nbsp;</td>\n"
                + "								<td width=\"200\">&nbsp;</td>\n"
                + "								<td width=\"200\">&nbsp;</td>\n"
                + "							</tr>\n"
                + "						</table>\n"
                + "					</div>\n"
                + "\n"
                + "					<div class='movableContent'>\n"
                + "						<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" width=\"600\" class=\"container\">\n"
                + "							<tr>\n"
                + "								<td width=\"100%\" colspan=\"3\" align=\"center\" style=\"padding-bottom:10px;padding-top:25px;\">\n"
                + "									<div class=\"contentEditableContainer contentTextEditable\">\n"
                + "					                	<div class=\"contentEditable\" align='center' >\n"
                + "					                  		<h2 >Espace sante Service</h2>\n"
                + "					                	</div>\n"
                + "					              	</div>\n"
                + "								</td>\n"
                + "							</tr>\n"
                + "							<tr>\n"
                + "								<td width=\"100\">&nbsp;</td>\n"
                + "								<td width=\"400\" align=\"center\">\n"
                + "									<div class=\"contentEditableContainer contentTextEditable\">\n"
                + "					                	<div class=\"contentEditable\" align='left' >\n"
                + "					                  		<p >Bonjour " + s + " " + user.getFirstname() + ",\n"
                + "					                  			<br/>\n"
                + "					                  			<br/>\n"
                + "												Votre mot de passe est :<br/>\n <span style=\"color:rgb(80,80,80);\">" + user.getPassword() + "</span></p>\n"
                + "					                	</div>\n"
                + "					              	</div>\n"
                + "								</td>\n"
                + "								<td width=\"100\">&nbsp;</td>\n"
                + "							</tr>\n"
                + "						</table>\n"
                    + "					</div>\n"
                    + "\n"
                    + "\n"
                    + "					<div class='movableContent'>\n"
                    + "						<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" width=\"600\" class=\"container\">\n"
                    + "							<tr>\n"
                    + "								<td width=\"100%\" colspan=\"2\" style=\"padding-top:65px;\">\n"
                    + "									<hr style=\"height:1px;border:none;color:#333;background-color:#ddd;\" />\n"
                    + "								</td>\n"
                    + "							</tr>\n"
                    + "							<tr>\n"
                    + "								<td width=\"60%\" height=\"70\" valign=\"middle\" style=\"padding-bottom:20px;\">\n"
                    + "									<div class=\"contentEditableContainer contentTextEditable\">\n"
                    + "					                	<div class=\"contentEditable\" align='left' >\n"
                    + "					                  		<span style=\"font-size:13px;color:#181818;font-family:Helvetica, Arial, sans-serif;line-height:200%;\">Sent to " + user.getEmail() + " by Espace sante  Service</span>\n"
                    + "											<br/>\n"
                    + "											<span style=\"font-size:11px;color:#555;font-family:Helvetica, Arial, sans-serif;line-height:200%;\"> Ariana Soghra Tunis | +216.54.550.468</span>\n"
                    + "											<br/>\n"
                    + "											<br/>\n"
                    + "					                	</div>\n"
                    + "					              	</div>\n"
                    + "								</td>\n"
                    + "								<td width=\"40%\" height=\"70\" align=\"right\" valign=\"top\" align='right' style=\"padding-bottom:20px;\">\n"
                    + "									<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align='right'>\n"
                    + "										<tr>\n"
                    + "											<td width='57%'></td>\n"
                    + "											<td valign=\"top\" width='34'>\n"
                    + "												<div class=\"contentEditableContainer contentFacebookEditable\" style='display:inline;'>\n"
                    + "							                        <div class=\"contentEditable\" >\n"
                    + "							                            <img src=\"http://www.theboatsafe.com/wp-content/uploads/shopp/Facebook.Circle.png\" data-default=\"placeholder\" data-max-width='30' data-customIcon=\"true\" width='30' height='30' alt='facebook' style='margin-right:40x;'>\n"
                    + "							                        </div>\n"
                    + "							                    </div>\n"
                    + "											</td>\n"
                    + "											<td valign=\"top\" width='34'>\n"
                    + "												<div class=\"contentEditableContainer contentTwitterEditable\" style='display:inline;'>\n"
                    + "							                      <div class=\"contentEditable\" >\n"
                    + "							                        <img src=\"http://icons.iconarchive.com/icons/sicons/basic-round-social/512/twitter-icon.png\" data-default=\"placeholder\" data-max-width='30' data-customIcon=\"true\" width='30' height='30' alt='twitter' style='margin-right:40x;'>\n"
                    + "							                      </div>\n"
                    + "							                    </div>\n"
                    + "											</td>\n"
                    + "											<td valign=\"top\" width='34'>\n"
                    + "												<div class=\"contentEditableContainer contentImageEditable\" style='display:inline;'>\n"
                    + "							                      <div class=\"contentEditable\" >\n"
                    + "														<img src=\"http://kizeeva.com/images/deliciousladies_google.png\" width=\"30\" height=\"30\" data-max-width=\"30\" alt='pinterest' style='margin-right:40x;' />\n"
                    + "							                      </div>\n"
                    + "							                    </div>\n"
                    + "											</td>\n"
                    + "										</tr>\n"
                    + "									</table>\n"
                    + "								</td>\n"
                    + "							</tr>\n"
                    + "						</table>\n"
                    + "					</div>\n"
                    + "\n"
                    + "\n"
                    + "				</td>\n"
                    + "			</tr>\n"
                    + "		</table>\n"
                    + "\n"
                    + "		\n"
                    + "		\n"
                    + "\n"
                    + "	</td></tr></table>\n"
                    + "	\n"
                    + "		</td>\n"
                    + "	</tr>\n"
                    + "	</table>\n"
                    + "	<!-- End of wrapper table -->\n"
                    + "\n"
                    + "<!--Default Zone\n"
                    + "\n"
                    + "    <div class=\"customZone\" data-type=\"image\">\n"
                    + "        <div class=\"movableContent\">\n"
                    + "        	<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" width=\"600\">        		\n"
                    + "				<tr><td colspan='3' height='30'></td></tr>\n"
                    + "				<tr>\n"
                    + "					<td width=\"50\">&nbsp;</td>\n"
                    + "					<td width=\"500\" colspan=\"3\" align=\"center\" style=\"padding-bottom:10px;padding-top:25px;\">\n"
                    + "						<div class=\"contentEditableContainer contentImageEditable\">\n"
                    + "			                <div class=\"contentEditable\">\n"
                    + "			                   <img src=\"/Users/oualha/NetBeansProjects/EspaceSante&BienEtre/src/images/doc.png\" data-default=\"placeholder\" data-max-width=\"500\">\n"
                    + "			                </div>\n"
                    + "			            </div>\n"
                    + "					</td>\n"
                    + "					<td width=\"50\">&nbsp;</td>\n"
                    + "				</tr>\n"
                    + "			</table>\n"
                    + "        </div>\n"
                    + "    </div>\n"
                    + "\n"
                    + "    <div class=\"customZone\" data-type=\"text\">\n"
                    + "        <div class='movableContent'>\n"
                    + "			<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" width=\"600\">\n"
                    + "				<tr><td colspan='3' height='30'></td></tr>\n"
                    + "				<tr>\n"
                    + "					<td width=\"50\">&nbsp;</td>\n"
                    + "					<td width=\"500\"  align=\"center\" style=\"padding-bottom:10px;padding-top:25px;\">\n"
                    + "						<div class=\"contentEditableContainer contentTextEditable\" >\n"
                    + "	                        <div class=\"contentEditable\" >\n"
                    + "	                            \n"
                    + "								<h2 >Make sure youâ€™re recognizable</h2>\n"
                    + "	                        </div>\n"
                    + "	                    </div>\n"
                    + "					</td>\n"
                    + "					<td width=\"50\">&nbsp;</td>\n"
                    + "				</tr>\n"
                    + "				<tr>\n"
                    + "					<td width=\"50\">&nbsp;</td>\n"
                    + "					<td width=\"500\" align=\"center\">\n"
                    + "						<div class=\"contentEditableContainer contentTextEditable\" >\n"
                    + "	                        <div class=\"contentEditable\" >\n"
                    + "	                            <p >\n"
                    + "								<p>Include both the name of the person whoâ€™s sending the email as well as the name of the company, and even better: send using your own domain.</p>\n"
                    + "								</p>\n"
                    + "	                        </div>\n"
                    + "	                    </div>\n"
                    + "						\n"
                    + "					</td>\n"
                    + "					<td width=\"50\">&nbsp;</td>\n"
                    + "				</tr>\n"
                    + "				<tr><td colspan=\"3\" height='30'></td></tr>\n"
                    + "				<tr>\n"
                    + "					<td width=\"50\">&nbsp;</td>\n"
                    + "					<td width=\"500\" align=\"center\" >\n"
                    + "						<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" width=\"400\" height=\"50\">\n"
                    + "							<tr>\n"
                    + "								<td bgcolor=\"#ED006F\" align=\"center\" style=\"border-radius:4px;\" width=\"400\" height=\"50\">\n"
                    + "									<div class=\"contentEditableContainer contentTextEditable\" >\n"
                    + "				                        <div class=\"contentEditable\" style='text-align:center;'>\n"
                    + "				                            <a target='_blank' href=\"[CLIENTS.WEBSITE]\" class='link2'>Read the 3 rules of email marketing sender etiquette</a>\n"
                    + "				                        </div>\n"
                    + "				                    </div>\n"
                    + "								</td>\n"
                    + "							</tr>\n"
                    + "\n"
                    + "						</table>\n"
                    + "					</td>\n"
                    + "					<td width=\"50\">&nbsp;</td>\n"
                    + "				</tr>\n"
                    + "				<tr><td height=\"10\" colspan=\"3\"></td></tr>\n"
                    + "			</table>\n"
                    + "		</div>\n"
                    + "    </div>\n"
                    + "\n"
                    + "    <div class=\"customZone\" data-type=\"imageText\">\n"
                    + "        <div class=\"movableContent\">\n"
                    + "            <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width='600'>\n"
                    + "            	<tr><td colspan=\"5\" height='30'></td></tr>\n"
                    + "                <tr>\n"
                    + "                	<td width='50'></td>\n"
                    + "                    <td valign=\"top\" width='150'>\n"
                    + "                        <div class=\"contentEditableContainer contentImageEditable\">\n"
                    + "                            <div class=\"contentEditable\">\n"
                    + "                                <img src=\"/Users/oualha/NetBeansProjects/e_shop/src/images/doc.png\" data-default=\"placeholder\" width='150' data-max-width=\"150\">\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </td>\n"
                    + "                    <td width='20'></td>\n"
                    + "                    <td valign=\"top\"  width='250'>\n"
                    + "                        <div class=\"contentEditableContainer contentTextEditable\">\n"
                    + "                            <div class=\"contentEditable\" style=\"color:#555;font-family:Helvetica, Arial, sans-serif;font-size:16px;line-height:160%;\">\n"
                    + "                                <h2 >This is a subtitle</h2>\n"
                    + "                                <p style=\"text-align:left;\">Etiam bibendum nunc in lacus bibendum porta. Vestibulum nec nulla et eros ornare condimentum. Proin facilisis, dui in mollis blandit. Sed non dui magna, quis tincidunt enim. Morbi vehicula pharetra lacinia.</p>\n"
                    + "                                <p style=\"text-align:right;\"><a target='_blank' href=\"\">Read more</a></p>\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </td>\n"
                    + "                    <td width='50'></td>\n"
                    + "                </tr>\n"
                    + "            </table>\n"
                    + "        </div>\n"
                    + "    </div>\n"
                    + "\n"
                    + "    <div class=\"customZone\" data-type=\"Textimage\">\n"
                    + "        <div class=\"movableContent\">\n"
                    + "            <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width='600'>\n"
                    + "            	<tr><td colspan=\"5\" height='30'></td></tr>\n"
                    + "                <tr>\n"
                    + "                	<td width='50'></td>\n"
                    + "                    <td valign=\"top\" width='230'>\n"
                    + "                        <div class=\"contentEditableContainer contentTextEditable\">\n"
                    + "                            <div class=\"contentEditable\" style=\"color:#555;font-family:Helvetica, Arial, sans-serif;font-size:16px;line-height:160%;\">\n"
                    + "                                <h2 >This is a subtitle</h2>\n"
                    + "                                <p style=\"text-align:left;\">Etiam bibendum nunc in lacus bibendum porta. Vestibulum nec nulla et eros ornare condimentum. Proin facilisis, dui in mollis blandit. Sed non dui magna, quis tincidunt enim. Morbi vehicula pharetra lacinia. </p>\n"
                    + "                                <p style=\"text-align:right;\"><a target='_blank' href=\"\">Read more</a></p>\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </td>\n"
                    + "                    <td width='20'></td>\n"
                    + "                    <td valign=\"top\" width='150'>\n"
                    + "                        <div class=\"contentEditableContainer contentImageEditable\">\n"
                    + "                            <div class=\"contentEditable\">\n"
                    + "                                <img src=\"/Users/oualha/NetBeansProjects/e_shop/src/images/doc.png\" data-default=\"placeholder\" width='150' data-max-width=\"150\">\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </td>\n"
                    + "                    <td width='50'></td>\n"
                    + "                </tr>\n"
                    + "            </table>\n"
                    + "        </div>\n"
                    + "    </div>\n"
                    + "\n"
                    + "    <div class=\"customZone\" data-type=\"textText\">\n"
                    + "        <div class=\"movableContent\">\n"
                    + "            <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width='600'>\n"
                    + "            	<tr><td height='30' colspan='5'></td></tr>\n"
                    + "                <tr>\n"
                    + "                	<td width='50'></td>\n"
                    + "                    <td valign=\"top\" width=\"230\">\n"
                    + "                        <div class=\"contentEditableContainer contentTextEditable\">\n"
                    + "                            <div class=\"contentEditable\" style=\"color:#555;font-family:Helvetica, Arial, sans-serif;font-size:16px;line-height:160%;\">\n"
                    + "                                <h2 >This is a subtitle</h2>\n"
                    + "                                <p >Etiam bibendum nunc in lacus bibendum porta. Vestibulum nec nulla et eros ornare condimentum. Proin facilisis, dui in mollis blandit. Sed non dui magna, quis tincidunt enim.</p>\n"
                    + "                                <p style=\"text-align:right;\"><a target='_blank' href=\"\">Read more</a></p>\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </td>\n"
                    + "                    <td width='40'></td>\n"
                    + "                    <td valign=\"top\" width='230'>\n"
                    + "                        <div class=\"contentEditableContainer contentTextEditable\">\n"
                    + "                            <div class=\"contentEditable\" style=\"color:#555;font-family:Helvetica, Arial, sans-serif;font-size:16px;line-height:160%;\">\n"
                    + "                                <h2 >This is a subtitle</h2>\n"
                    + "                                <p style=\"text-align:left;\">Etiam bibendum nunc in lacus bibendum porta. Vestibulum nec nulla et eros ornare condimentum. Proin facilisis, dui in mollis blandit. Sed non dui magna, quis tincidunt enim.</p>\n"
                    + "                                <p style=\"text-align:right;\"><a target='_blank' href=\"\">Read more</a></p>\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </td>\n"
                    + "                    <td width='50'></td>\n"
                    + "                </tr>\n"
                    + "            </table>\n"
                    + "        </div>\n"
                    + "    </div>\n"
                    + "\n"
                    + "    <div class=\"customZone\" data-type=\"qrcode\">\n"
                    + "        <div class=\"movableContent\">\n"
                    + "            <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width='600'>\n"
                    + "            	<tr><td height='30' colspan='5'></td></tr>\n"
                    + "                <tr>\n"
                    + "                	<td width='50'></td>\n"
                    + "                    <td valign=\"top\" >\n"
                    + "                        <div class=\"contentQrcodeEditable contentEditableContainer\">\n"
                    + "                            <div class=\"contentEditable\">\n"
                    + "                                <img src=\"/Users/oualha/NetBeansProjects/e_shop/src/images/doc.png\" width=\"75\" height=\"75\" data-default=\"placeholder\">\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </td>\n"
                    + "                    <td width='20'></td>\n"
                    + "                    <td valign=\"top\">\n"
                    + "                        <div class=\"contentEditableContainer contentTextEditable\">\n"
                    + "                            <div class=\"contentEditable\" style=\"color:#555;font-family:Helvetica, Arial, sans-serif;font-size:16px;line-height:160%;\">\n"
                    + "                                <h2 >This is a subtitle</h2>\n"
                    + "                                <p style=\"text-align:left;\">Etiam bibendum nunc in lacus bibendum porta. Vestibulum nec nulla et eros ornare condimentum. Proin facilisis, dui in mollis blandit. Sed non dui magna, quis tincidunt enim. Morbi vehicula pharetra lacinia. Cras tincidunt, justo at fermentum feugiat, eros orci accumsan dolor, eu ultricies eros dolor quis sapien. Curabitur in turpis sem, a sodales purus. Pellentesque et risus at mauris aliquet gravida.</p>\n"
                    + "                                <p style=\"text-align:left;\">Integer in elit in tortor posuere molestie non a velit. Pellentesque consectetur, nisi a euismod scelerisque.</p>\n"
                    + "                                <p style=\"text-align:right;\"><a target='_blank' href=\"\">Read more</a></p>\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </td>\n"
                    + "                    <td width='50'></td>\n"
                    + "                </tr>\n"
                    + "            </table>\n"
                    + "        </div>\n"
                    + "    </div>\n"
                    + "\n"
                    + "    <div class=\"customZone\" data-type=\"social\">\n"
                    + "        <div class=\"movableContent\" align='center'>\n"
                    + "            <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width='600'>\n"
                    + "            	<tr><td height='30' colspan='5'></td></tr>\n"
                    + "                <tr>\n"
                    + "                	<td width='50'></td>\n"
                    + "                    <td valign=\"top\" width=\"230\" align='center'>\n"
                    + "                        <div class=\"contentEditableContainer contentFacebookEditable\">\n"
                    + "                            <div class=\"contentEditable\">\n"
                    + "                                <img data-default=\"placeholder\" src=\"images/facebook.png\" data-max-width='60' data-customIcon=\"true\" data-noText=\"true\" width='60' height='60'>\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                        <div class=\"contentEditableContainer contentTextEditable\">\n"
                    + "                            <div class=\"contentEditable\" style=\"color:#555;font-family:Helvetica, Arial, sans-serif;font-size:16px;line-height:160%;\">\n"
                    + "                                <h2 >Facebook</h2>\n"
                    + "                                <p>Like us on Facebook to keep up with our news, updates and other discussions.</p>\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </td>\n"
                    + "                    <td width='40'></td>\n"
                    + "                    <td valign=\"top\" width=\"230\" align='center'>\n"
                    + "                        <div class=\"contentEditableContainer contentTwitterEditable\">\n"
                    + "                            <div class=\"contentEditable\">\n"
                    + "                                <img data-default=\"placeholder\" src=\"images/twitter.png\" data-max-width='60' data-customIcon=\"true\" data-noText=\"true\" width='60' height='60'>\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                        <div class=\"contentEditableContainer contentTextEditable\">\n"
                    + "                            <div class=\"contentEditable\" style=\"color:#555;font-family:Helvetica, Arial, sans-serif;font-size:16px;line-height:160%;\">\n"
                    + "                                <h2 >Twitter</h2>\n"
                    + "                                <p>Follow us on twitter to stay up to date with company news and other information.</p>\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </td>\n"
                    + "                    <td width='50'></td>\n"
                    + "                </tr>\n"
                    + "            </table>\n"
                    + "        </div>\n"
                    + "    </div>\n"
                    + "\n"
                    + "    <div class=\"customZone\" data-type=\"twitter\">\n"
                    + "        <div class=\"movableContent\" align='center'>\n"
                    + "            <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width='600'>\n"
                    + "            	<tr><td height='30' colspan='3'></td></tr>\n"
                    + "                <tr>\n"
                    + "                	<td width='50'></td>\n"
                    + "                    <td valign=\"top\" align='center'>\n"
                    + "                        <div class=\"contentEditableContainer contentTwitterEditable\">\n"
                    + "                            <div class=\"contentEditable\">\n"
                    + "                                <img data-default=\"placeholder\" src=\"images/twitter.png\" data-max-width='60' data-customIcon=\"true\" data-noText=\"true\" width='60' height='60'>\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                        <div class=\"contentEditableContainer contentTextEditable\">\n"
                    + "                            <div class=\"contentEditable\" style=\"color:#555;font-family:Helvetica, Arial, sans-serif;font-size:16px;line-height:160%;\">\n"
                    + "                                <h2 >Twitter</h2>\n"
                    + "                                <p>Follow us on twitter to stay up to date with company news and other information.</p>\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </td>\n"
                    + "                    <td width='50'></td>\n"
                    + "                </tr>\n"
                    + "            </table>\n"
                    + "        </div>\n"
                    + "   </div>\n"
                    + "\n"
                    + "    <div class=\"customZone\" data-type=\"facebook\" >\n"
                    + "        <div class=\"movableContent\" align='center'>\n"
                    + "            <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width='600'>\n"
                    + "            	<tr><td height='30' colspan='3'></td></tr>\n"
                    + "                <tr>\n"
                    + "                	<td width='50'></td>\n"
                    + "                    <td valign=\"top\" align='center'>\n"
                    + "                        <div class=\"contentEditableContainer contentFacebookEditable\">\n"
                    + "                            <div class=\"contentEditable\">\n"
                    + "                                <img data-default=\"placeholder\"  data-max-width='60' data-customIcon=\"true\" data-noText=\"true\" width='60' height='60'>\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                        <div class=\"contentEditableContainer contentTextEditable\">\n"
                    + "                            <div class=\"contentEditable\" style=\"color:#555;font-family:Helvetica, Arial, sans-serif;font-size:16px;line-height:160%;\">\n"
                    + "                                <h2>Facebook</h2>\n"
                    + "                                <p>Like us on Facebook to keep up with our news, updates and other discussions.</p>\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </td>\n"
                    + "                    <td width='50'></td>\n"
                    + "                </tr>\n"
                    + "            </table>\n"
                    + "        </div>\n"
                    + "    </div>\n"
                    + "\n"
                    + "    <div class=\"customZone\" data-type=\"gmap\">\n"
                    + "        <div class=\"movableContent\">\n"
                    + "            <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width='600'>\n"
                    + "                <tr><td height='30' colspan='5'></td></tr>\n"
                    + "                <tr>\n"
                    + "                	<td width='50'></td>\n"
                    + "                    <td valign=\"top\" >\n"
                    + "                        <div class=\"contentGmapEditable contentEditableContainer\">\n"
                    + "                            <div class=\"contentEditable\">\n"
                    + "                                <img src=\"/applications/Mail_Interface/3_3/modules/User_Interface/core/v31_campaigns/images/neweditor/default/gmap_example.png\" width=\"75\" data-default=\"placeholder\">\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </td>\n"
                    + "                    <td width='20'></td>\n"
                    + "                    <td valign=\"top\">\n"
                    + "                        <div class=\"contentEditableContainer contentTextEditable\">\n"
                    + "                            <div class=\"contentEditable\" style=\"color:#555;font-family:Helvetica, Arial, sans-serif;font-size:16px;line-height:160%;\">\n"
                    + "                                <h2 >This is a subtitle</h2>\n"
                    + "                                <p style=\"text-align:left;\">Etiam bibendum nunc in lacus bibendum porta. Vestibulum nec nulla et eros ornare condimentum. Proin facilisis, dui in mollis blandit. Sed non dui magna, quis tincidunt enim. Morbi vehicula pharetra lacinia. Cras tincidunt, justo at fermentum feugiat, eros orci accumsan dolor, eu ultricies eros dolor quis sapien. Curabitur in turpis sem, a sodales purus. Pellentesque et risus at mauris aliquet gravida.</p>\n"
                    + "                                <p style=\"text-align:left;\">Integer in elit in tortor posuere molestie non a velit. Pellentesque consectetur, nisi a euismod scelerisque.</p>\n"
                    + "                                <p style=\"text-align:right;\"><a target='_blank' href=\"\">Read more</a></p>\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </td>\n"
                    + "                    <td width='50'></td>\n"
                    + "                </tr>\n"
                    + "            </table>\n"
                    + "        </div>\n"
                    + "    </div>\n"
                    + "\n"
                    + "\n"
                    + "	 <div class=\"customZone\" data-type=\"colums1v2\"><div class='movableContent'>\n"
                    + "          	<table width=\"600\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" >\n"
                    + "	            <tr><td height=\"30\" colspan='3'>&nbsp;</td></tr>\n"
                    + "	            <tr>\n"
                    + "	            	<td width='50'></td>\n"
                    + "	              	<td width='500' align=\"center\" valign=\"top\" class=\"newcontent\">\n"
                    + "	                \n"
                    + "	              	</td>\n"
                    + "	              	<td width='50'></td>\n"
                    + "	            </tr>\n"
                    + "          	</table>\n"
                    + "    	</div>\n"
                    + "      </div>\n"
                    + "\n"
                    + "      <div class=\"customZone\" data-type=\"colums2v2\"><div class='movableContent'>\n"
                    + "          <table width=\"600\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" >\n"
                    + "	            <tr><td height=\"30\" colspan='3'>&nbsp;</td></tr>\n"
                    + "	            <tr>\n"
                    + "	            	<td width='50'></td>\n"
                    + "	              	<td width='235' align=\"center\" valign=\"top\" class=\"newcontent\">\n"
                    + "	                \n"
                    + "	              	</td>\n"
                    + "					<td width='30'></td>\n"
                    + "	              	<td width='235' align=\"center\" valign=\"top\" class=\"newcontent\">\n"
                    + "	                \n"
                    + "	              	</td>\n"
                    + "	              	<td width='50'></td>\n"
                    + "	            </tr>\n"
                    + "          	</table>\n"
                    + "    	</div>\n"
                    + "      </div>\n"
                    + "\n"
                    + "      <div class=\"customZone\" data-type=\"colums3v2\"><div class='movableContent'>\n"
                    + "         <table width=\"600\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" >\n"
                    + "	            <tr><td height=\"30\" colspan='3'>&nbsp;</td></tr>\n"
                    + "	            <tr>\n"
                    + "	            	<td width='50'></td>\n"
                    + "	              	<td width='158' align=\"center\" valign=\"top\" class=\"newcontent\">\n"
                    + "	                \n"
                    + "	              	</td>\n"
                    + "					<td width='12'></td>\n"
                    + "	              	<td width='158' align=\"center\" valign=\"top\" class=\"newcontent\">\n"
                    + "	                \n"
                    + "	              	</td>\n"
                    + "					<td width='12'></td>\n"
                    + "	              	<td width='158' align=\"center\" valign=\"top\" class=\"newcontent\">\n"
                    + "	                \n"
                    + "	              	</td>\n"
                    + "	              	<td width='50'></td>\n"
                    + "	            </tr>\n"
                    + "          	</table>\n"
                    + "    	</div>\n"
                    + "      </div>\n"
                    + "\n"
                    + "      <div class=\"customZone\" data-type=\"textv2\">\n"
                    + "		<div class=\"contentEditableContainer contentTextEditable\" >\n"
                    + "            <div class=\"contentEditable\" >\n"
                    + "                \n"
                    + "				<h2 >Make sure youâ€™re recognizable</h2>\n"
                    + "            </div>\n"
                    + "        </div>\n"
                    + "		<div class=\"contentEditableContainer contentTextEditable\" >\n"
                    + "            <div class=\"contentEditable\" >\n"
                    + "				<p>Include both the name of the person whoâ€™s sending the email as well as the name of the company, and even better: send using your own domain.</p>\n"
                    + "            </div>\n"
                    + "        </div>\n"
                    + "		<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" width=\"79%\" height=\"50\">\n"
                    + "			<tr>\n"
                    + "				<td bgcolor=\"#ED006F\" align=\"center\" style=\"border-radius:4px;\" width=\"100%\" height=\"50\">\n"
                    + "					<div class=\"contentEditableContainer contentTextEditable\" >\n"
                    + "                        <div class=\"contentEditable\" style='text-align:center;'>\n"
                    + "                            <a target='_blank' href=\"[CLIENTS.WEBSITE]\" class='link2'>Read the 3 rules of email marketing sender etiquette</a>\n"
                    + "                        </div>\n"
                    + "                    </div>\n"
                    + "				</td>\n"
                    + "			</tr>\n"
                    + "		</table>\n"
                    + "      </div>\n"
                    + "\n"
                    + "\n"
                    + "\n"
                    + "\n"
                    + "-->\n"
                    + "<!--Default Zone End-->\n"
                    + "\n"
                    + "</body>\n"
                    + "</html>");
        TrayNotification tray = new TrayNotification("Felicitation!", "un mail de verification de votre mot de passer vous a ete envoyer", NotificationType.SUCCESS);
           tray.showAndWait();
           cancel();
        }
        else{ 
            buttonError.setText("Invalide Email");
            buttonError.setVisible(true);
        }
    }
    
     @Override
    public void initialize(URL url, ResourceBundle rb) {
        buttonError.setVisible(false);
         buttonError.setOnMouseClicked((MouseEvent event) -> {
             buttonError.setVisible(false);
        });
       
    
                 
        
        // TODO
    }    

    @FXML
    private void Anuuler(ActionEvent event) throws IOException {
         cancel();
    }
    
    public void cancel()
    {
        AnimationGenerator animationGenerator = new AnimationGenerator();
        animationGenerator.applyFadeAnimationOn(stage.getScene().getRoot(), 500, 1.0f, 0f, event1 -> {
            try {
                EspaceSanteBienEtre.currentUser = null;
                loginWindow = FXMLLoader.load(EspaceSanteBienEtre.class.getResource("/GUI/Login.fxml"));
                loginScene = new Scene(loginWindow);
                EspaceSanteBienEtre.stage.setScene(loginScene);
                stage.centerOnScreen();
                EspaceSanteBienEtre.loginWindow.setOpacity(1f);
                animationGenerator.applyFadeAnimationOn(EspaceSanteBienEtre.loginWindow, 500, 0f, 1.0f, null);
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
        });
    }
    

    
}
